# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_runSentenceTransformer_wrappers", use_symbols = TRUE, package_name = "runSentenceTransformer")

#' @usage NULL
#' @useDynLib runSentenceTransformer, .registration = TRUE
NULL

#' only Bert models a currently supported and the following files are expected:
#' - config.json
#' - tokenizer.json
#' - model.safetensors
#' @internal
string_embedding <- function(x, path) .Call(wrap__string_embedding, x, path)

#' @internal
rust_pwd <- function(path) .Call(wrap__rust_pwd, path)


# nolint end
